---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sink-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sink-db
  template:
    metadata:
      labels:
        app: sink-db
    spec:
      containers:
      - name: sink-db
        image: postgres:11.1
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: sink-db
spec:
  selector:
    app: sink-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maturity-sink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maturity-sink
  template:
    metadata:
      labels:
        app: maturity-sink
    spec:
      containers:
      - name: maturity-sink
        image: khinkali/maturity-sink:0.0.3
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: maturity-sink
spec:
  selector:
    app: maturity-sink
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
    nodePort: 30222
  type: NodePort